---
- name: configure ldap
  hosts: all
  become: True

  vars:
    CA_CERTDIR: /etc/openldap/cacerts
    HOSTNAME: myhostname

  tasks:
  - name: Install openldap-clients sssd oddjob-mkhomedir
    yum:
      name: '{{item}}'
      state: installed
    with_items:
      - openldap-clients
      - sssd
      - oddjob-mkhomedir

  - name: Recreate ca cert dir and contents
    file:
      path: '{{CA_CERTDIR}}'
      state: '{{item}}'
    with_items:
      - absent
      - directory

  - name: Copy over Federal Common Policy CA Certs
    copy:
      src: templates/{{item}}
      dest: /tmp/{{item}}
    with_items:
      - dhs-ca4-3.crt
      - dhs-ca4-2.crt
      - us-treasury-root.crt
      - federal-common-policy-ca.crt

  - name: Install Federal Common Policy CA Certs
    shell: certutil -d {{ CA_CERTDIR }} -A -n {{ item }},,
    with_items:
      - "'DHS-CA4-3' -i /tmp/dhs-ca4-3.crt -t CT"
      - "'DHS-CA4-2' -i /tmp/dhs-ca4-2.crt -t CT"
      - "'US Treasury Root CA' -i /tmp/us-treasury-root.crt -t CT"
      - "'Federal Common Policy CA' -i /tmp/federal-common-policy-ca.crt -t CT"

  - name: Copy over ldap conf file
    copy:
      src: templates/ldap.conf
      dest: /etc/openldap/ldap.conf

  - name: Remove NSS LDAP
    file:
      path: '{{item}}'
      state: absent
    with_items:
      - /etc/pam_ldap.conf
      - /etc/nslcd.conf
      - /etc/ldap.conf
      - /etc/ldap.secret

  - name: Stop NSLCD & NSCD
    service:
      name: '{{item}}'
      state: stopped
    with_items:
      - nscd
      - nslcd
    ignore_errors: yes

  - name: Remove nss-pam-ldapd
    yum:
      name: nss-pam-ldapd
      state: removed

  #In the STIG baselines, it is explicitly forbidden to use authconfig. Opted not to change.
  - name: Configure the system to use SSSD
    command: authconfig --enablesssd --enablesssdauth --enablelocauthorize --disableldapauth --enablemkhomedir --update

  - name: Configure SSSD
    template:
      src: templates/sssd.j2
      dest: /etc/sssd/sssd.conf
      owner: root
      group: root
      mode: 0600
      setype: sssd_conf_t

  - name: Set up NSSwitch
    copy:
      src: templates/nsswitch.conf
      dest: /etc/nsswitch.conf
      backup: yes
      mode: 0644

  - name: Restart SSSD, MegaBus, and OddJobD
    service:
      name: '{{item}}'
      state: restarted
      enabled: True
    with_items:
      - sssd
      - messagebus
      - oddjobd