---
- name: configure Spacewalk client
  hosts: all
  become: True

  tasks:
  - name: rhel activation key
    set_fact:
      activation_key: 1-rhel-{{ ansible_distribution_major_version }}-x86_64-server-key
      distro_shortname: rhel
    when: (ansible_distribution == "Red Hat Enterprise Linux") or (ansible_distribution == "RedHat")

  - name: centos activation key
    set_fact:
      activation_key: 1-centos-{{ ansible_distribution_major_version }}-x86_64-server-key
      distro_shortname: centos
    when: ansible_distribution == "CentOS"

  - name: remove spacewalk cert chain
    yum:
      name: rhn-org-trusted-ssl-cert
      state: removed

  - name: install cert chain
    shell: "rpm -Uvh http://{{ spacewalk_server }}/pub/rhn-org-trusted-ssl-cert-1.0-2.noarch.rpm"

  - name: register spacewalk client
    shell: "rhnreg_ks --force --serverUrl=https://{{ spacewalk_server }}/XMLRPC --activationkey={{ activation_key }}"
    when: activation_key is defined

  - name: install channel GPG key
    rpm_key:
      state: present
      key: https://{{spacewalk_server }}/pub/repos/{{ distro_shortname }}/{{ ansible_distribution_major_version }}/x86_64/os/RPM-GPG-KEY-redhat-release