---

#
#Raw module Bit Defender Playbook. Writing a Bit Defender module is advised over using this.
#

- name: Install Bit Defender
  hosts: all
  tasks:
  - name: Check if defender is there
    win_stat:
      path: 'C:\Program Files\Bitdefender\Endpoint Security\epconsole.exe'
    register: fileinfo

  - name: Mount Drive
    raw: 'net use Z: \\gnuthpmgns0010v.tvlport.net\windows_repository\Products\Bitdefender /user:galileo\poshadmin PASSWORD'
    when: fileinfo.stat.exists != True

  - name: Copy over 64-bit corp install
    raw: 'xcopy "Z:\Corporate\epskit_x64\*" "C:\BitdefenderClient\*"'
    when: ansible_architecture == '64-bit' and fileinfo.stat.exists != True and ansible_fqdn|search('corp') == True

  - name: Copy over x86 corp install
    raw: 'xcopy "Z:\Corporate\epskit_x86\*" "C:\BitdefenderClient\*"'
    when: ansible_architecture != '64-bit' and fileinfo.stat.exists != True and ansible_fqdn|search('corp') == True

  - name: Copy over 64-bit comm install
    raw: 'xcopy "Z:\Commercial\epskit_x64\*" "C:\BitdefenderClient\*"'
    when: ansible_architecture == '64-bit' and fileinfo.stat.exists != True and ansible_fqdn|search('corp') == False

  - name: Copy over x86 comm install
    raw: 'xcopy "Z:\Commercial\epskit_x86\*" "C:\BitdefenderClient\*"'
    when: ansible_architecture != '64-bit' and fileinfo.stat.exists != True and ansible_fqdn|search('corp') == False

  - name: Unmount drive
    raw: 'net use Z: /DELETE'
    when: fileinfo.stat.exists != True

  - name: Install the proper version x86
    raw: 'C:\BitdefenderClient\epskit_x86.exe /bdparams /silent'
    when: fileinfo.stat.exists != True and ansible_architecture != '64-bit'

  - name: Install the proper version 64-bit
    raw: 'C:\BitdefenderClient\epskit_64-bit.exe /bdparams /silent'
    when: fileinfo.stat.exists != True and ansible_architecture == '64-bit'