---

- name: Install Bit Defender
  hosts: all
  tasks:
  - name: Check if defender is there
    win_stat:
      path: 'C:\Program Files\Bitdefender\Endpoint Security\epconsole.exe'
    register: fileinfo

  - name: Copy over template
    win_template:
      src: templates/powershell_copy.j2
      dest: 'C:\temp\powershell_copy.ps1'
    when: fileinfo.stat.exists != True

  - name: Run Powershell Script (Duh)
    raw: 'powershell.exe -File C:\temp\powershell_copy.ps1'

  - name: Install the proper version x86
    raw: 'C:\BitdefenderClient\epskit_x86.exe /bdparams /silent'
    when: fileinfo.stat.exists != True and ansible_architecture != '64-bit'

  - name: Install the proper version 64-bit
    raw: 'C:\BitdefenderClient\epskit_64-bit.exe /bdparams /silent'
    when: fileinfo.stat.exists != True and ansible_architecture == '64-bit'